config/routes.rb
Rails.application.routes.draw do

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  resources :orders do
      member do
        get :pay_with_credit_card
      end
    end
  
  root "products#index"

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items, source: :product

	def find_cart_item(product)
	  cart_items.find_by(product_id: product)
	end

	def add_product_to_cart(product)
		ci = cart_items.build
		ci.product = product
		ci.save
	end

	def total_price
		sum = 0

		cart_items.each do |cart_item|
		      sum += (cart_item.product.price * cart_item.quantity)
		end
		sum
	end

	def clean!
		cart_items.destroy_all
	end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user

	has_many :items, class_name: "OrderItem", dependent: :destroy
	has_one :info, class_name: "OrderInfo", dependent: :destroy

	accepts_nested_attributes_for :info

	 before_create :generate_token

	include AASM

	  aasm do
	    state :order_placed, initial: true
	    state :paid
	    state :shipping
	    state :shipped
	    state :order_cancelled
	    state :good_returned


	    event :make_payment, after_commit: :pay! do
	      transitions from: :order_placed, to: :paid
	    end

	    event :ship do
	      transitions from: :paid,         to: :shipping
	    end

	    event :deliver do
	      transitions from: :shipping,     to: :shipped
	    end

	    event :return_good do
	      transitions from: :shipped,      to: :good_returned
	    end

	    event :cancell_order do
	      transitions from: [:order_placed, :paid], to: :order_cancelled
	    end
	  end 

	def generate_token
	  self.token = SecureRandom.uuid
	end

	def set_payment_with!(method)
	   self.update_columns(payment_method: method )
	 end

	 def pay!
	   self.update_columns(is_paid: true )
	 end

	def build_item_cache_from_cart(cart)
	    cart.items.each do |cart_item|
	      item = items.build
	      item.product_name = cart_item.title
	      item.quantity = cart.find_cart_item(cart_item).quantity
	      item.price = cart_item.price
	      item.save
	    end
	  end

	  def calculate_total!(cart)
	    self.total = cart.total_price
	    self.save
	end
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
	belongs_to :order

	 validates :billing_name,     presence: true
	 validates :billing_address,  presence: true
	 validates :shipping_name,    presence: true
	 validates :shipping_address, presence: true
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product

	mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :photo

	accepts_nested_attributes_for :photo
end

app/models/productrail.rb
class Productrail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders
  
  def admin?
   	is_admin
  end 

  def to_admin
  	self.update_columns(is_admin: true)
  end

  def to_normal
  	self.update_columns(is_admin: false)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def render_cart_total_price(cart)
		cart.total_price
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def render_order_state(order)
	   t("orders.order_state.#{order.aasm_state}")
	end

	def render_order_paid_state(order)
	  if order.is_paid?
	    "已付款"
	  else
	    "未付款"
	  end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/commom/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">ArtStore</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to("Products", products_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "#" do  %>
            購物車 <i class="fa fa-shopping-cart"> </i> (0)
         <% end %>
       </li>

        <% if !current_user %>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li>
                  <%= link_to("Admin 選單", admin_products_path ) %>
                </li>
                <% end %>
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_adminMenu.html.erb
<ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
	<li> <%= link_to("Products", admin_products_path) %> 
	</li>
  <li> <%= link_to("Users", admin_users_path) %> 
  </li>
</ul>

app/views/common/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= @product.title %></li>
</ol>

app/views/common/_footer.html.erb
<footer>
The “Artstore” Project by Growth School, forked by galearii.
</footer>

app/views/common/_header.html.erb
<nav class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Artstore</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="main-menu">
    <ul class="nav navbar-nav">
      <li><%= link_to("Products", products_path) %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to(carts_path) do  %>
          My Cart <i class="fa fa-shopping-cart"></i> (<%= render_cart_items_count(current_cart) %>)
        <% end %>
      </li>

      <% if !user_signed_in? %>
        <li><%= link_to("Sign In", new_user_session_path) %></li>
        <li><%= link_to("Sign Up", new_user_registration_path) %></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
            <li><%= link_to("Administration", admin_products_path) %></li>
            <li><%= link_to("All Orders", admin_orders_path) %></li>
            <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to("My Account", edit_user_registration_path) %></li>
            <li><%= link_to("My Orders", account_orders_path) %>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
          </ul> <!-- /.dropdown-menu -->
        </li> <!-- /.dropdown -->

      <% end %>
    </ul>
  </div>
</nav>

app/views/common/_nav.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ArtStore', root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
        <li>
          <%= link_to "#" do  %>
            購物車 <i class="fa fa-shopping-cart"> </i> (0)
          <% end %>
        </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li class="dropdown-header">產品</li>
                <li><%= link_to '所有產品', admin_products_path %></li>
                <li><%= link_to("新增產品", new_admin_product_path) %></li>
                <li role="separator" class="divider"></li>
              <% end %>
              <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<!--       <a class="navbar-brand" href="/">ArtStore</a>
 -->    
      <a class="navbar-brand" href="/"> Dell NoteBook Shop </a>
 </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to("Products", products_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to carts_path do %>
        Shopping Cart <i class="fa fa-shopping-cart"> </i> (<%= render_cart_items_count(current_cart) %>)
        <% end %>
      </li>

        <% if !current_user %>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <% if current_user.admin? %>
               <li>
                 <%= link_to("Admin 選單", admin_products_path ) %>
               </li>
             <% end %>
             <li>
                           <%= link_to("個人訂單列表", account_orders_path ) %>
                          </li>
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_navbar_mobile.html.erb
      <ul id="nav-mobile" class="side-nav">
       <li>
         <%= link_to carts_path do  %>
           購物車 <i class="fa fa-shopping-cart"> </i> ( <%= render_cart_items_count(current_cart) %> )  NT$ <%= render_cart_total_price(current_cart) %>
         <% end %>
       </li>
        <% if !current_user %>
          <li> <%= link_to("註冊", new_user_registration_path) %> </li>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        </li>
        <% else %>
          <li id="nav-mobile" class="side-nav">


             <% if current_user.admin? %>
               <li>
                 <%= link_to("Admin 選單", admin_products_path ) %>
               </li>
             <% end %>
             <li>
               <%= link_to("個人訂單列表", account_orders_path ) %>
             </li>
             <li>
               <%= link_to("帳戶設定", edit_user_registration_path) %> </li>
             </li>
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>

app/views/common/_order_index.html.erb
<h2>訂單列表 </h2>

<table class="table table-bordered">

  <thead>
    <tr>
      <th>#</th>
      <th>生成時間</th>
      <th>訂購者</th>
      <th>訂單狀態</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td> <%= link_to(order.id, admin_order_path(order) ) %> </td>
        <td> <%= render_order_timestamp(order) %> </td>
        <td> <%= order.user.email %></td>
        <td> <%= render_order_state(order) %> </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/common/_order_show.html.erb
<div class="col-md-12">

 <h2> 訂單明細 (<%= render_order_paid_state(@order) %>) </h2>

 <%= render_order_options_for_admin(@order) %>

 <table class="table table-bordered">

   <thead>
     <tr>
       <th width="80%">商品明細</th>
       <th>單價</th>
       <th>數量</th>
     </tr>
   </thead>

   <tbody>
     <% @order_items.each do |order_item| %>
       <tr>
         <td>
           <%= order_item.product_name %>
         </td>
         <td> <%= order_item.price %> </td>
         <td> <%= order_item.quantity %> </td>
       </tr>
     <% end %>
   </tbody>

 </table>

 <div class="total clearfix">
   <span class="pull-right">
     <span> 總計 <%= @order.total %> NTD
   </span>
 </div>

 <hr>
  <h2> 寄送資訊 </h2>

  <table class="table table-striped table-bordered">

   <tbody>
     <tr>
       <td> 訂購人 </td>
     </tr>

     <tr>
       <td>
         <%= @order_info.billing_name %> - <%= @order_info.billing_address %>
       </td>
     </tr>

     <tr>
       <td> 收貨人 </td>
     </tr>

     <tr>
       <td>
         <%= @order_info.shipping_name %> - <%= @order_info.shipping_address %>
       </td>
     </tr>

   </tbody>

 </table>

</div>

app/views/common/_product_item.html.erb
<div class="col-xs-6 col-md-3">
  <%= link_to product_path(product) do %>
    <%= render_product_photo(product.default_photo) %>
  <% end %>
    <%= product.title %> $ <%= product.price %>
</div>

app/views/common/_product_modify.html.erb
<%= simple_form_for [:admin, @product ] , :html => { :class => "form form-horizontal"  } do |f| %>

  <div class="form-group">

    <div class="col-sm-10">
      <%= f.input :title %>
    </div>
  </div>

  <div class="form-group">

    <div class="col-sm-10">
      <%= f.input :description, :as => :text %>
    </div>
  </div>

  <div class="form-group">

    <div class="col-sm-1">
      <%= f.input :quantity %>
    </div>
  </div>

  <div class="form-group">

    <div class="col-sm-1">
      <%= f.input :price %>
    </div>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photos do |c| %>
      <%= c.input :image , :as => :file %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-default" , :disable_with => 'Submiting...' %>
  </div>

<% end %>

app/views/common/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li> <%= link_to("Products", admin_products_path) %> </li>
  <li> <%= link_to("Orders", admin_orders_path) %> </li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "ArtStore", '/', class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Products", products_path %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to carts_path do %>
          Shopping Cart <i class="fa fa-shopping-cart"></i> (<%= render_cart_items_count(current_cart) %>)
        <% end %>
      </li>
      <li>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= "Hi, #{current_user.email}" %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
              <li><%= link_to "Admin menu", admin_products_path %></li>
            <% end %>
            <li><%= link_to "Orders", account_orders_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>