config/routes.rb
Rails.application.routes.draw do

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  resources :orders do
      member do
        get :pay_with_credit_card
      end
    end
  
  root "products#index"

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items, source: :product

	def find_cart_item(product)
	  cart_items.find_by(product_id: product)
	end

	def add_product_to_cart(product)
		ci = cart_items.build
		ci.product = product
		ci.save
	end

	def total_price
		sum = 0

		cart_items.each do |cart_item|
		      sum += (cart_item.product.price * cart_item.quantity)
		end
		sum
	end

	def clean!
		cart_items.destroy_all
	end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user

	has_many :items, class_name: "OrderItem", dependent: :destroy
	has_one :info, class_name: "OrderInfo", dependent: :destroy

	accepts_nested_attributes_for :info

	 before_create :generate_token

	include AASM

	  aasm do
	    state :order_placed, initial: true
	    state :paid
	    state :shipping
	    state :shipped
	    state :order_cancelled
	    state :good_returned


	    event :make_payment, after_commit: :pay! do
	      transitions from: :order_placed, to: :paid
	    end

	    event :ship do
	      transitions from: :paid,         to: :shipping
	    end

	    event :deliver do
	      transitions from: :shipping,     to: :shipped
	    end

	    event :return_good do
	      transitions from: :shipped,      to: :good_returned
	    end

	    event :cancell_order do
	      transitions from: [:order_placed, :paid], to: :order_cancelled
	    end
	  end 

	def generate_token
	  self.token = SecureRandom.uuid
	end

	def set_payment_with!(method)
	   self.update_columns(payment_method: method )
	 end

	 def pay!
	   self.update_columns(is_paid: true )
	 end

	def build_item_cache_from_cart(cart)
	    cart.items.each do |cart_item|
	      item = items.build
	      item.product_name = cart_item.title
	      item.quantity = cart.find_cart_item(cart_item).quantity
	      item.price = cart_item.price
	      item.save
	    end
	  end

	  def calculate_total!(cart)
	    self.total = cart.total_price
	    self.save
	end
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
	belongs_to :order

	 validates :billing_name,     presence: true
	 validates :billing_address,  presence: true
	 validates :shipping_name,    presence: true
	 validates :shipping_address, presence: true
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product

	mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :photo

	accepts_nested_attributes_for :photo
end

app/models/productrail.rb
class Productrail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders
  
  def admin?
   	is_admin
  end 

  def to_admin
  	self.update_columns(is_admin: true)
  end

  def to_normal
  	self.update_columns(is_admin: false)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def index
  	@products = Product.all
  end

  def edit
  	@product = Product.find(params[:id])

  	if @product.photo.present?
  		@photo = @product.photo
  	else
  		@photo = @product.build_photo
  	end
  end

  def update
  	@product = Product.find(params[:id])

  	if @product.update(product_params)
  		redirect_to admin_products_path
  	else
  		render :edit
  	end
  end

  # def show
  # 	@product = Product.find(params[:id])
  # end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description,
    							                  :quantity, :price,
    							                  photo_attributes: [:image, :id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	before_action :authenticate_user!, only: [:checkout]

 def checkout
   @order = current_user.orders.build
   @info = @order.build_info
 end

 def clean
   current_cart.clean!
   flash[:warning] = "已清空購物車"
   redirect_to carts_path
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def about

end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def add_to_cart
		@product = Product.find(params[:id])

		if !current_cart.items.include?(@product)
			current_cart.add_product_to_cart(@product)
			flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
		else
			flash[:warning] = "你的購物車內已有此物品"
		end
		redirect_to :back
	end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def render_cart_total_price(cart)
		cart.total_price
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def render_order_state(order)
	   t("orders.order_state.#{order.aasm_state}")
	end

	def render_order_paid_state(order)
	  if order.is_paid?
	    "已付款"
	  else
	    "未付款"
	  end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/_edit_product_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :title, label:"標題" %>
  <%= f.input :description, label:"敘述" %>
  <%= f.input :quantity, label:"數量" %>
  <%= f.input :price, label:"價格"  %>
  <div class="form_group">
    <%= f.simple_fields_for :photos do |c| %>
      <% c.input :image, label:"圖片", as: :file %>
    <% end %>
  </div>
  <%= f.button :submit, "儲存", data: {disable_with: "Submitting"} %>
<% end %>

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>

  <div class="form-group">
    <%= f.input :title, required: true, label: "Product Name", input_html: { class: "form-control" } %>
    <%= f.input :description, required: true, label: "Product Description", input_html: { class: "form-control" } %>
    <%= f.input :quantity, required: true, label: "Quantity", input_html: { class: "form-control" } %>
    <%= f.input :price, required: true, label: "Price", input_html: { class: "form-control", placeholder: "$" } %>
  </div>

  <% if params[:action] == "edit" %>
    <% if @photo.image.present? %>
      <h4>Current Product Photo</h4>
      <%= image_tag(@photo.image.thumb.url) %>

      <div class="form-group">
        <%= f.simple_fields_for :photo do |c| %>
          <%= c.input :image, label: "Update Product Photo", as: :file %>
        <% end %>
      </div>
    <% else %>
      <div class="form-group">
        <%= f.simple_fields_for :photo do |c| %>
          <%= c.input :image, as: :file %>
        <% end %>
      </div>
    <% end %>
  <% elsif params[:action] == "new" %>
    <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image, label: "Product Photo", as: :file %>
    <% end %>
    </div>
  <% end %>


  <%= f.submit @form_options[:submit_text], class: "btn btn-primary", data: { disable_with: @form_options[:disable_text] } %>
  <%= link_to("Cancel", admin_products_path, class: "btn btn-sm btn-warning") %>

  <% if params[:action] == "edit" %>
    <%= link_to("Delete", admin_product_path(@product), class: "btn btn-danger pull-right", method: :delete, data: { confirm: "Are you sure?" }) %>
  <% end %>

<% end %>

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product] do |f|
  =f.input :title
  =f.input :description
  =f.input :quantity
  =f.input :price

  =f.submit "Submit", data: { disable_with: "Submitting"} 

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= link_to render_product_image(product.default_image), product %></td>
  <td><%= product.title %></td>
  <td><%= product.price %></td>
  <td><%= link_to "Edit", edit_admin_product_path(product) %></td>
</tr>

app/views/admin/products/edit.html.erb
<h2> Create Products</h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <% if @photo.image.present? %>
    <span>目前商品圖</span> <br>
    <%= image_tag(@photo.image.thumb.url) %>
   <% end %>

   <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image , as: :file %>
    <% end %>
   </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.photo.present? %>
              <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
        <%= link_to("Edit", edit_admin_product_path(product)) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

app/views/admin/products/index.html.haml
%ul
  - @products.each do |product|
    %li= link_to product.title, admin_product_path(product)

app/views/admin/products/new.html.erb
<h2> Create Products</h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="form-group">
  <%= f.simple_fields_for :photo do |c| %>
    <%= c.input :image , as: :file %>
  <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/new.html.haml
%h1.text-center New Product
= render 'form'

app/views/admin/products/show.html.erb
<div class="row">
	<div class="col-md-6">
		<% if @product.photo.present? %>
		  <%= image_tag(@product.photo.image.medium.url, class: "thumbmail") %>
		<% else %>
		  <%= image_tag("http://placehold.it/400x400&text=No pic", class: "thumbmail") %>
		<% end %>
	</div>
	<div class="col-md-6">
		<h2> <%= @product.title %> </h2>
		<div style="height 100px;">
			<p>
				<%= @product.description %>
			</p>
		</div>
		<div> 數量 : <%= @product.quantity %> </div>
		<div class="product-price"> $ <%= @product.price %> </div>
		<div class="pull-right">
		</div>
	</div>
</div>

app/views/products/_category_item.html.erb
    <div class="col-md-3">
      <p class="lead">Shop Name</p>
      <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
      </div>
    </div>

app/views/products/_product.html.erb
<div class="col-xs-6 col-md-3">
  <%= link_to render_product_image(product.default_image), product_path(product) %>
  <div>
    <%= product.title %>
  </div>
  <div>
    <%= "$ #{product.price}" %>
  </div>
</div>

app/views/products/_product_item.html.erb
<% products.each do |product| %>

  <div class="col-xs-6 col-md-3">

    <%= link_to product_path(product) do %>
      <%= render_product_photo(product.default_photo) %>
    <% end %>

    <%=product.title %> $ <%=product.price %>

  </div>
<% end %>

app/views/products/_product_item_html.erb
<% products.each do |product| %>
  <div class = "col-xs-6 col-md-3">
    <%= link_to product_path(product) do %>
      <%= render_product_photo(product.default_photo) %>
    <%= end %>

    <%= product.title %> $ <%= product.price %>
  </div>
<% end %>

app/views/products/_product_items.html.erb
<% @products.each do |product| %>
  <div class="col-xs-6 col-md-3">

    <%= link_to product_path(product) do %>
      <%= render_product_photo(product.default_photo) %>
    <% end %>

    <%= product.title %> $ <%= product.price %>
  </div>
<% end %>
	

app/views/products/_slide_item.html.erb
      <div class="row carousel-holder">

        <div class="col-md-12">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="10000">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>

      </div>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.photo.present? %>
          <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= product.title %> $ <%= product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.photo.present? %>
      <%= image_tag(@product.photo.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> 數量 : <%= @product.quantity %> </div>
    <div class="product-price"> $ <%= @product.price %> </div>
    <div class="pull-right">
    <% if @product.quantity > 0 %>
      <%= link_to("加入購物車", add_to_cart_product_path(@product), method: :post, :class => "btn btn-primary btn-lg btn-danger") %>
    <% else %>
           已銷售一空，無法購買
    <% end %>
    </div>
  </div>
</div>