config/routes.rb
Rails.application.routes.draw do

  resources :items, controller: "cart_items"

  namespace :account do
    resources :orders
  end

  resources :orders do
      member do
        get :pay_with_credit_card
      end
    end
  
  root "products#index"

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items, source: :product

	def find_cart_item(product)
	  cart_items.find_by(product_id: product)
	end

	def add_product_to_cart(product)
		ci = cart_items.build
		ci.product = product
		ci.save
	end

	def total_price
		sum = 0

		cart_items.each do |cart_item|
		      sum += (cart_item.product.price * cart_item.quantity)
		end
		sum
	end

	def clean!
		cart_items.destroy_all
	end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user

	has_many :items, class_name: "OrderItem", dependent: :destroy
	has_one :info, class_name: "OrderInfo", dependent: :destroy

	accepts_nested_attributes_for :info

	 before_create :generate_token

	include AASM

	  aasm do
	    state :order_placed, initial: true
	    state :paid
	    state :shipping
	    state :shipped
	    state :order_cancelled
	    state :good_returned


	    event :make_payment, after_commit: :pay! do
	      transitions from: :order_placed, to: :paid
	    end

	    event :ship do
	      transitions from: :paid,         to: :shipping
	    end

	    event :deliver do
	      transitions from: :shipping,     to: :shipped
	    end

	    event :return_good do
	      transitions from: :shipped,      to: :good_returned
	    end

	    event :cancell_order do
	      transitions from: [:order_placed, :paid], to: :order_cancelled
	    end
	  end 

	def generate_token
	  self.token = SecureRandom.uuid
	end

	def set_payment_with!(method)
	   self.update_columns(payment_method: method )
	 end

	 def pay!
	   self.update_columns(is_paid: true )
	 end

	def build_item_cache_from_cart(cart)
	    cart.items.each do |cart_item|
	      item = items.build
	      item.product_name = cart_item.title
	      item.quantity = cart.find_cart_item(cart_item).quantity
	      item.price = cart_item.price
	      item.save
	    end
	  end

	  def calculate_total!(cart)
	    self.total = cart.total_price
	    self.save
	end
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
	belongs_to :order

	 validates :billing_name,     presence: true
	 validates :billing_address,  presence: true
	 validates :shipping_name,    presence: true
	 validates :shipping_address, presence: true
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product

	mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :photo

	accepts_nested_attributes_for :photo
end

app/models/productrail.rb
class Productrail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders
  
  def admin?
   	is_admin
  end 

  def to_admin
  	self.update_columns(is_admin: true)
  end

  def to_normal
  	self.update_columns(is_admin: false)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	layout "admin"

	before_action :authenticate_user!
	before_action :admin_required

    def index
      	@users = User.all
    end

    def to_admin
      	@user = User.find(params[:id])
      	@user.to_admin

      	redirect_to admin_users_path
    end

    def to_normal
        @user = User.find(params[:id])
        @user.to_normal

        redirect_to admin_users_path
    end
   
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	before_action :authenticate_user!, only: [:checkout]

 def checkout
   @order = current_user.orders.build
   @info = @order.build_info
 end

 def clean
   current_cart.clean!
   flash[:warning] = "已清空購物車"
   redirect_to carts_path
 end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :configure_permitted_parameters

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def render_cart_total_price(cart)
		cart.total_price
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def render_order_state(order)
	   t("orders.order_state.#{order.aasm_state}")
	end

	def render_order_paid_state(order)
	  if order.is_paid?
	    "已付款"
	  else
	    "未付款"
	  end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/edit.html.erb
<h2>變更會員權限</h2>
<%= simple_form_for [:admin, @user] do |f| %>
    <div class="group">
      <%= f.label :email %>: <%= @user.email %>
    </div>

    <div class="group">
      <%= f.input :is_admin, as: :boolean, checked_value: true, unchecked_value: false %>
    </div>
    <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/admin/users/index.html.erb
<h2>使用者列表</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>權限</th>
      <th>功能</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <% if user.admin? %>
           管理者
         <% else %>
           一般使用者
         <% end %>
        </td>
        <td>
          <% if user.admin? %>
            <%= link_to("轉為一般使用者", to_normal_admin_user_path(user), method: :post, class: "btn btn-info") %>
         <% else %>
            <%= link_to("轉為管理者", to_admin_admin_user_path(user), method: :post, class: "btn btn-primary") %>
         <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
	<hr>
  <%= link_to "我已經有帳號了，讓我登入", new_session_path(resource_name), class: "btn btn-primary" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
	<hr>
  我還沒有帳號，<%= link_to "註冊新帳號", new_registration_path(resource_name), class: "btn btn-danger btn-xs" %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘記密碼?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>